travis:
  secure:
    BINSTAR_TOKEN: w41Ibpl+kZXUmMjhdpNzPZTpx9iF9kHns9Aow5SvE8eExRLkgvpGn8lNnhIq3/0orSvtqKqdf005xs1V6UT181agy5SC5BchdvXHAInJ21BTc1RrIHMwtDnC/IjgnOkZZQ/YQMOu6AZKJBCHOEyInRqZZ3b27kv1/d3BQV/1ajPwPpBibeIyE38W80ubsi7cuyJSQuFPYmENkhGIcLSpE3WJF5ow5T8URh/TO4+7XTGZrRc21xxCtDRVYBsRuyDPyTwP94kkziF5X4wbGfSbrtTsBEoyoSJvevM0LSWYkATe7kMX733BXGVIdRi3m0g4hDRtYP2Fy6SQsa4R5D2ZrBlQHv7xIFyaa+gdfE1qkQmUrOP7FJL8QZaybehFf13b/jtFVHPF2h7aARM1v+2Urpi2L/giDhRN6hPSLDEwkc2Sbj/YewsqYPt8Z61OVSBSk8RSJGXszPvmD7v2TEaJ3sjmXlGCXxcbgIGRcX3BsCQuDwhpNRs/AwUWHCcVP5E6szwDYg7K0vmrlSLcXb7w1wET7GstqO4GXrWPmmDP1qPN8ZhXEIiaccdzM2UOO/LtUQciZHEALFYBWiQloFAj6eqiJpEk/BiZploemnVWYXp7dDwjtlJz7SbYx/lg9GzgIlS2zwrHnN4CsBl35bT6ZZ6fYRPMGbj0rtAO1ccgJG8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
