appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: jTJ8JnzBL6YaQjgUNNU+XEK48KPEagt3UvJuopGEDV4Kr1BpbRTqwCIfvzj7l1wEdpjKc7uMu1kg0ONo5VxVZ6h2GNUkimVF8VTAhP43XNfl2/Abab3sfMKgWwn+m8qieUAwN1aF2j2BYWWfO6QA+3rlfUq2UP0jWu9TKmJHGzQ994iU25/Y8SE5BB5gndCUkjMWLhxi9Rf9RccwNhldFBjKaXaGjcXDZNkZtzlTGGptsDwxckO/oHJ9syNBjnEtqyJB064gzNKOSnRpWbNnQS/5pTpyw6IzcJbydFTY+3RE4BTnNETg9wSqPIKcZ4sSDU7slX1QccG6Tu2r6xnEIXG9JnanGTdNSg37ROFfd4FJBxxsHlUPZsZCOsqot6gr/knVrdtwCF/hhfZjmWITXAPMJVOJhKhvq2BctFu6lQA9AOdScM3U0kwtj+IN7Tdanzeb+KJeTkV0sczAZyyKs5JjatYbP+okGRl8NbpPg/EWCb6YljgmaZbnDnksFivopv/4i0jNLJNGyduDAWpGSXBvCYWzg2Eun23UdBZkOd1JxtTpv6mBAJwpklmKeGoHadYddyZdaAi4qpMpyOv6IUjsyDnO4RTwkyEGwvErA6lEfnhPrHiFIz7t7Ht0p3RWO36vtHgIqiWGapvxOnia5wwJrDJ7eKvgo7HFTRbgynY=}
bot:
  automerge: true
